### ISSUE TITLE
tab缩进乱码

### ISSUE THREAD

**Issue by AnDeltas** [FishionYu/typora-blubook-theme#1]
```
这样的代码块中tab显示正常
```
`tab显示错误`
正常文本中tab缩进也会有乱码

**Comment by FishionYu** [comment]
我测试正常，可以贴图吗

**Comment by FishionYu** [comment]
@AnDeltas A
[测试](https://cdn.jsdelivr.net/gh/FishionYu/Rayyu-sPic@master/img/tab%E6%B5%8B%E8%AF%95.gif)

**Comment by FishionYu** [comment]
![tab测试2](https://user-images.githubusercontent.com/20253239/90089778-dba16400-dd54-11ea-92dc-dfff484bebf9.gif)

**Comment by FishionYu** [comment]
最新的发布已修复
