### ISSUE TITLE
在code block 里面不能用shift + tab 退缩进

### ISSUE THREAD

**Issue by TAN-ZIXUAN** [FishionYu/typora-blubook-theme#10]
code bock很棒，体验和真的editor一样。
但是我发现在这里面不能用 shift + tab 退缩进， 只能一点点退格删除，对于写python来说有点麻烦。

**Comment by FishionYu** [comment]
这个应该是Typora编辑器的问题，测试其他主题也是这样子。
经测试是这样的：回车换行后的自动缩进没办法 shift + tab 退缩进，行内 tab 后是可以 shift + tab 退缩进的。
我会再持续关注一下这个问题。
