### ISSUE TITLE
TODO 框可能出现异常错位

### ISSUE THREAD

**Issue by reposkeeper** [FishionYu/typora-blubook-theme#13]
![image](https://user-images.githubusercontent.com/23925710/91928584-04db6180-ed0f-11ea-8f2b-868d0e4dfe8a.png)
如上图，新建文件，创建任务列表，写几个待办，切换文件，有几率会出现上述的情况

**Comment by FishionYu** [comment]
你的md文件可以贴在这里吗，我试了来回切换并没有出现，想看一下具体情况
