### ISSUE TITLE
hope to get dark theme

### ISSUE THREAD

**Issue by hong-tm** [FishionYu/typora-blubook-theme#14]
nice build theme for typora, wish to get a derk theme support as fast as possible.

**Comment by FishionYu** [comment]
I have a plan to build the dark version, but it will take some time.

**Comment by hong-tm** [comment]
ok, thanks bro, hope to see you soon!

**Comment by Henning16** [comment]
i made a similar theme (it is not up on the typora page yet tho) which has support for a dark theme. Maybe you check it out over here: [Gitbook theme](https://github.com/Henning16/typora-gitbook-theme)

**Comment by chill-swift** [comment]
Sooooo appreciate the awesome theme, thx bro~
also looking for dark mode~

**Comment by FishionYu** [comment]
It's seem nice!

**Comment by FishionYu** [comment]
> i made a similar theme (it is not up on the typora page yet tho) which has support for a dark theme. Maybe you check it out over here: [Gitbook theme](https://github.com/Henning16/typora-gitbook-theme)

It's seem nice!
