### ISSUE TITLE
TAB

### ISSUE THREAD

**Issue by 850756306** [FishionYu/typora-blubook-theme#2]

**Comment by 850756306** [comment]
TAB 缩进的时候，行首有一个乱码符号  
win10系统  typora是官网下的最新版本
![image](https://user-images.githubusercontent.com/44258916/90091210-66d02900-dd58-11ea-880f-6a443e7afd3a.png)

**Comment by FishionYu** [comment]
抱歉，平时只测了macOS下的情况，我在windows上看一下

**Comment by AnDeltas** [comment]
我也是这样, 系统是manjaro, 有人贴图了我就不搞了:smile:

**Comment by FishionYu** [comment]
下了一个虚拟机，测试最新的发布已修复
