### ISSUE TITLE
Smart quotes

### ISSUE THREAD

**Issue by admin-teametry** [FishionYu/typora-blubook-theme#22]
Hi,

I like your theme and I like the font. I have a problem writing in english with activated "smart quotes" on MacOS. If Ir write "I'm" it will be converted to "I' m" This behaviour seems to be a font issue, because with other fonts I don't have the problem.

Any ideas how to solve it? Or do you know a font which comes near to "Glow Sans SC"?

Thanks for your good work 🙂 
Andreas

**Comment by FishionYu** [comment]
Can you provide screenshot from your 'Typora setting - Markdown - Smart Punctuation' and your 'System setting - Keyboard - Text - Use smart quotes' ?

Like:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/20253239/97377609-68db6a00-18fb-11eb-929e-106c1163945b.png">
<img width="500" alt="image" src="https://user-images.githubusercontent.com/20253239/97377656-7e509400-18fb-11eb-8827-52fe5da122ad.png">

Someone also found this problem not long ago, I will test the font problem again.

**Comment by admin-teametry** [comment]
Here they are :-)

<img width="665" alt="Screenshot 2020-10-28 at 07 40 18" src="https://user-images.githubusercontent.com/22169059/97401553-4ba19e00-18f1-11eb-9c1e-ffebadbe1e29.png">
<img width="691" alt="Screenshot 2020-10-28 at 07 39 52" src="https://user-images.githubusercontent.com/22169059/97401577-55c39c80-18f1-11eb-8907-b35dd4d6c1de.png">

**Comment by Fastidious** [comment]
@admin-teametry your issue doesn't relate to the font, but since you asked about one, I have found that [Atkinson Hyperlegible](https://www.brailleinstitute.org/freefont) is just perfect for extensive documentation. I have replaced the one on the theme with it.

**Comment by admin-teametry** [comment]
> @admin-teametry your issue might not relate to the font, but since you asked about one, I have found that [Atkinson Hyperlegible](https://www.brailleinstitute.org/freefont) is just perfect for extensive documentation. I have replaced the one on the theme with it.

Great, the font looks really good :-) When do you think, will you update the git repo for your theme?

Thanks
Andreas
