### ISSUE TITLE
关于Windows的样式变形问题

### ISSUE THREAD

**Issue by Zephyr-Liu** [FishionYu/typora-blubook-theme#24]
![image](https://user-images.githubusercontent.com/61276495/98923661-ea8fe200-250e-11eb-945c-ef64cc7bc3d0.png)
虽然大大主要做Mac上面的 但是windowns用户还是希望救一下

**Comment by Zephyr-Liu** [comment]
![image](https://user-images.githubusercontent.com/61276495/98923850-23c85200-250f-11eb-9965-466a7a619dab.png)

**Comment by Zephyr-Liu** [comment]
Win102019LTSB版本,未开任何字体渲染软件.比如mactype。

**Comment by Zephyr-Liu** [comment]
![image](https://user-images.githubusercontent.com/61276495/98926061-ca155700-2511-11eb-988c-5ad3c8d02911.png)

**Comment by Zephyr-Liu** [comment]
希望大大早日看到

**Comment by FishionYu** [comment]
这个框框之前windows测试的时候没留意到。。

**Comment by Zephyr-Liu** [comment]
哈哈 这两个搜索框都出现了样式变形的问题。
![image](https://user-images.githubusercontent.com/61276495/99235425-c8f56a00-2830-11eb-91e2-ca105c829e0c.png)
这里还有两个选项按钮也显示出了问题

**Comment by Zephyr-Liu** [comment]
没事没事 我来提醒你[doge][doge]

**Comment by FishionYu** [comment]
ok~晚些时候我调整一下

**Comment by FishionYu** [comment]
部分稍微调整了下，但是虚拟机体验过于糟糕......有没有使用windows的小伙伴看一下问题

**Comment by Zephyr-Liu** [comment]
我来了

**Comment by Zephyr-Liu** [comment]
使用了最新版
使用过于糟糕

**Comment by FishionYu** [comment]
windows下错位严重，大部分windows的问题我还没修复，我抽空再看下，要是有win平台的小伙伴可以帮忙看下问题就好了。

**Comment by FishionYu** [comment]
@liuhao326 感谢提交的pr，看了下大部分已经可以了

**Comment by liuhao326** [comment]
不用谢👋 @FishionYu
