### ISSUE TITLE
设置代码格式的时候 下方代码语言种类显示问题

### ISSUE THREAD

**Issue by Zephyr-Liu** [FishionYu/typora-blubook-theme#26]
![image](https://user-images.githubusercontent.com/61276495/99339275-d4907180-28c0-11eb-9f5b-8e999c1b0edb.png)
颜色太深 导致看不出代码语言的种类

**Comment by Zephyr-Liu** [comment]
![image](https://user-images.githubusercontent.com/61276495/99339372-086b9700-28c1-11eb-9dba-5e89e23a3105.png)

**Comment by Zephyr-Liu** [comment]
问题总结:
![image](https://user-images.githubusercontent.com/61276495/99339605-6b5d2e00-28c1-11eb-823f-7435b1b00569.png)
查找框 - 代码格式显示 
期待尽快优化
我先换回默认的了 
期待大大早日修复

**Comment by FishionYu** [comment]
为什么我这里看是正常的诶...
<img width="1580" alt="image" src="https://user-images.githubusercontent.com/20253239/99344613-6f8e4900-28cb-11eb-8f6b-9f732ae90b13.png">

**Comment by FishionYu** [comment]
windows下也正常
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/20253239/99344868-0955f600-28cc-11eb-8d7e-2a1122140198.png">

**Comment by Zephyr-Liu** [comment]
奇怪了  我试试卸载重装 看看

**Comment by Zephyr-Liu** [comment]
不行 我卸载重装了 还是不行

**Comment by Zephyr-Liu** [comment]
![image](https://user-images.githubusercontent.com/61276495/99370254-69fb2800-28f8-11eb-8211-e4022b111e53.png)
我尽力了 我卸载重装很多次了还是样式有点问题
呜呜呜 人间失格

**Comment by FishionYu** [comment]
你把typora和windows版本贴一下？

**Comment by Zephyr-Liu** [comment]
![image](https://user-images.githubusercontent.com/61276495/99932300-95679200-2d92-11eb-9bd5-7fe13fc44151.png)
![image](https://user-images.githubusercontent.com/61276495/99932343-ad3f1600-2d92-11eb-84ec-48e16f4b8b72.png)

**Comment by FishionYu** [comment]
你试一下最新的release，应该没问题了

**Comment by Zephyr-Liu** [comment]
是的
