### ISSUE TITLE
对主题的建议

### ISSUE THREAD

**Issue by Zephyr-Liu** [FishionYu/typora-blubook-theme#27]
前言：
对不起大大 我实在太喜欢这个主题了。
但是！
用起来有点吃力
所以我按照我最中意的样子跟您反馈啦
![image](https://user-images.githubusercontent.com/61276495/99369173-11775b00-28f7-11eb-8445-039383ab4721.png)
![image](https://user-images.githubusercontent.com/61276495/99369220-1f2ce080-28f7-11eb-9217-41dbc92698cc.png)
首先上一张默认和您主题的对比
![image](https://user-images.githubusercontent.com/61276495/99369700-b5f99d00-28f7-11eb-9b6a-b2553e86a150.png)
建议都写在图上了 非常感谢开发者的成果
我也非常希望大大的东西能够更受欢迎
当然这是我的一点拙见
平台:windowns
版本：LTSB 2019

**Comment by FishionYu** [comment]
我在考虑后期出个脚本，可以快速根据不同的喜好改一些内容🤔

**Comment by FishionYu** [comment]
可以在blubook.css里面修改，直接右键.css用记事本打开
图片的问题：搜索`img {`，然后把`max-width: 80%` 改为`max-width: 100%`
区域大小问题：搜索`#write {`，就是最上面的`width: 90%; max-width: 700px;`根据自己喜好调整一下
