### ISSUE TITLE
sequence代码展示问题

### ISSUE THREAD

**Issue by jiash** [FishionYu/typora-blubook-theme#28]
你好，你的主题能够方便的区分1，2，3级标题。我非常喜欢。但是有点小问题，请您看看呢。

sequence，编辑的时候，预览图和下方的文字重叠了。而且代码段右下角的代码类型看不清呢。
![image](https://user-images.githubusercontent.com/19601719/100174557-9cfc7780-2f07-11eb-8821-2805c8f2491c.png)

![image](https://user-images.githubusercontent.com/19601719/100174528-8eae5b80-2f07-11eb-87cf-9c8aee467e73.png)

**Comment by FishionYu** [comment]
新版的commit已经修复完成，你可以直接在原文件中下载更新

**Comment by jiash** [comment]
非常感谢
