### ISSUE TITLE
关于windowns的搜索框字体样式变形等问题

### ISSUE THREAD

**Issue by Zephyr-Liu** [FishionYu/typora-blubook-theme#31]
![image](https://user-images.githubusercontent.com/61276495/100701129-f8cc7200-33d9-11eb-83f7-763b147e1873.png)
![image](https://user-images.githubusercontent.com/61276495/100701160-04b83400-33da-11eb-9518-825f631cf118.png)
![image](https://user-images.githubusercontent.com/61276495/100701176-0da90580-33da-11eb-9c4a-6f6da9f6035a.png)
这三处的的搜索框都有问题
- 偏好设置-通用
- 主页查找搜索框
- Ctrl+F 文本搜索框

**Comment by liuhao326** [comment]
最新代码已解决该问题(#29,#24,#30)，请重新下载**源码**，或直接复制 [blubook.css](https://github.com/FishionYu/typora-blubook-theme/blob/master/blubook.css) 的内容并将其替换到 Typora 主题文件夹的 blubook.css 文件中。 @Zephyr-Liu

**Comment by FishionYu** [comment]
我也已经打包发布了release

**Comment by Zephyr-Liu** [comment]
感谢开发者  已解决  牛逼！！！！！！
