### ISSUE TITLE
这些很好看的emoji表情能在标题中自动生成吗？

### ISSUE THREAD

**Issue by LCheee** [FishionYu/typora-blubook-theme#37]

**Comment by LCheee** [comment]
是需要自己粘进去嘛？

**Comment by Higurashi-kagome** [comment]
主题不支持自动生成 emoji，要在文档中添加表情需要复制表情后粘贴，或者输入表情所对应的快捷代码。比如，输入 `:question:` 之后你将得到一个问号（❓）。 @LCheee

**Comment by FishionYu** [comment]
需要自己粘贴或者输入对应的序号来查找哦 `一般是两个冒号之间加一串字符`
![image](https://user-images.githubusercontent.com/20253239/105945540-6c1ff680-60a0-11eb-872b-c11109c52835.png)
