### ISSUE TITLE
代码文本字样不能加粗显示

### ISSUE THREAD

**Issue by hjzCy** [FishionYu/typora-blubook-theme#38]
普通代码样式：`code`
加粗代码样式：**`bold code`**
但是，在 blubook 中，以下代码样式的显示效果一样：
```
`code`
**`code`**
```

**Comment by Higurashi-kagome** [comment]
感谢你的使用和反馈 @hjzCy 。[最新代码](https://github.com/FishionYu/typora-blubook-theme/blob/master/blubook.css)应该已经修复该问题，可以试试。
