### ISSUE TITLE
==xxx== 高亮颜色不搭

### ISSUE THREAD

**Issue by reposkeeper** [FishionYu/typora-blubook-theme#4]
![image](https://user-images.githubusercontent.com/23925710/90306365-23fc8580-deff-11ea-9fda-fff38a0a2d27.png)
像上图，使用了 `==xxx==` 的颜色和主题不太搭调，可否换个颜色

**Comment by FishionYu** [comment]
高亮的颜色我会再配一下

**Comment by FishionYu** [comment]
新版已上线
