### ISSUE TITLE
大纲标题行内代码背景色会覆盖

### ISSUE THREAD

**Issue by icefery** [FishionYu/typora-blubook-theme#44]
复现：
```markdown
### 三级标题 `Authorization`
```
希望能更改一下大纲视图的颜色

**Comment by Higurashi-kagome** [comment]
感谢反馈，请问你的意思是否是需要去除大纲中的行内代码？或许在视图大纲中显示行内代码才是我们所期盼的行为。事实上，大多数主题都会将标题中的行内代码呈现在大纲中：

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/51501079/109089493-50b21500-774c-11eb-948a-2acabe4f735a.png)

![image](https://user-images.githubusercontent.com/51501079/109089527-61628b00-774c-11eb-9241-d88941f9a618.png)

![image](https://user-images.githubusercontent.com/51501079/109089545-69222f80-774c-11eb-9fb3-b99069887d70.png)

</details>

**Comment by icefery** [comment]
我可能没表达清楚。
我的问题是：这款主题大纲背景色深蓝色的，标题字体颜色是白色的，标题中行内代码背景色也是白色的，那么行内代码就看不清了。
类似这样（其它级标题也是）：
```markdown
###### 5.1.2 Uniapp 请求获取不到自定义响应头 `Authorization`
```
![image](https://user-images.githubusercontent.com/61737634/109093702-c1106480-7753-11eb-9629-ec1769b41f60.png)
> 我觉得这个应该不太可能是我电脑的问题，可能是一点小 bug ，希望作者能稍微修改一下

**Comment by Higurashi-kagome** [comment]
明白了，的确有过这个问题，在[最新版本](https://github.com/FishionYu/typora-blubook-theme/blob/master/blubook.css)中已修复：

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/51501079/109094840-9aebc400-7755-11eb-8495-eeb8d069e045.png)

</details>

**Comment by icefery** [comment]
昂好的，我是直接在`realease`下的，没发现早已经修复了，感谢。
