### ISSUE TITLE
uneven space alignment

### ISSUE THREAD

**Issue by guesswh0** [FishionYu/typora-blubook-theme#45]
Source Mode:
<img width="279" alt="Screen Shot 2021-03-01 at 16 01 21" src="https://user-images.githubusercontent.com/10531675/109482021-b2091980-7aa7-11eb-855b-ceecc283dbb1.png">

View Mode: (Blubook theme)
<img width="370" alt="Screen Shot 2021-03-01 at 16 02 15" src="https://user-images.githubusercontent.com/10531675/109482029-b46b7380-7aa7-11eb-9178-98fef1c3da26.png">

View Mode: (Github theme)
<img width="327" alt="Screen Shot 2021-03-01 at 16 03 16" src="https://user-images.githubusercontent.com/10531675/109482034-b5040a00-7aa7-11eb-9134-ba14b2ffc667.png">

**Comment by Higurashi-kagome** [comment]
Thanks for your feedback! Try to change [L442](https://github.com/FishionYu/typora-blubook-theme/blob/4325ad05d26356169b9c88941c83a2b3b5dd9ccc/blubook.css#L442) to `font-family: inherit;`. It might be helpful. Tell me if it works, please.

**Comment by guesswh0** [comment]
Thanks to you for quick reply! Well changing `font-family` didn't solved the issue. Alignment is still with slight slope.

**Comment by Higurashi-kagome** [comment]
I see, could you please provide the test text?

**Comment by guesswh0** [comment]
Just type this simple example in Typora `Source Mode`, alignment of text is done with 'spaces' not 'tabs'.

**Comment by guesswh0** [comment]
```
`a`       123  
`ab`     123  
`abc`   123  
```

Remove code block after copying to typora

**Comment by Higurashi-kagome** [comment]
Thanks, it's helpful @guesswh0 . I just know this is caused by the `font-size` style of the `code` element:

<details>
<summary>Details</summary>

![demo](https://user-images.githubusercontent.com/51501079/109496132-34570500-7acb-11eb-8a50-1901774b1275.gif)

</details>

But I don’t know how to fix the alignment problem while keeping the font unchanged now. @FishionYu

**Comment by guesswh0** [comment]
Well, seems like its come from typora`s space and tab inconsistence. Thank you. Love your theme anyway.

**Comment by Higurashi-kagome** [comment]
Thanks for your kindness.

**Comment by Higurashi-kagome** [comment]
Hi @guesswh0👋!  Fixed this in #46,  could have a try for the new [css](https://github.com/FishionYu/typora-blubook-theme/blob/master/blubook.css) file.
