### ISSUE TITLE
图片宽度增大

### ISSUE THREAD

**Issue by Higurashi-kagome** [FishionYu/typora-blubook-theme#50]
注意到图片宽度比行长短：

<details>
<summary>Details</summary>

![demo1](https://user-images.githubusercontent.com/51501079/113411728-1f7ed180-93e9-11eb-8fed-62fdcd5fc4d9.png)

</details>

这使得某些时候无法看清图片中的细节。

或许可通过去除

```CSS
img {
  max-width: 80%;
  ...
}
```

中的 `max-width` 属性来增大图片宽度（使其与行长相同）？

这是我尝试去除后得到的效果：

<details>
<summary>Details</summary>

![demo2](https://user-images.githubusercontent.com/51501079/113411904-9025ee00-93e9-11eb-9f19-41995c2f4392.png)

</details>

**Comment by FishionYu** [comment]
这个可以优化，因为整个文章宽度较小，即使图片撑满也不会很丑
