### ISSUE TITLE
编写公式的时候会会连公式一起染色了

### ISSUE THREAD

**Issue by qiyang-ustc** [FishionYu/typora-blubook-theme#6]
如下图所示：
![image](https://user-images.githubusercontent.com/24543212/90524864-27af3700-e1a1-11ea-9212-da061ce0525e.png)

**Comment by FishionYu** [comment]
这个我用的比较少，忘记适配了，我会修复一下

**Comment by FishionYu** [comment]
最新版已修复

**Comment by herfrain** [comment]
我下载了最新版Blubook_v1.6.0，但是好像没变，还是黑色看不清

**Comment by herfrain** [comment]
> 我下载了最新版Blubook_v1.6.0，但是好像没变，还是黑色看不清
修改了一下blubook.css中的这个
.code-tooltip {
  box-shadow: 0 1px 1px 0 rgba(0, 28, 36, .3);
  border-top: 1px solid #eef2f2;
  background: #183055;
  border-radius: 6px;
  color: white; // 显示白色字体
}
