### ISSUE TITLE
TODO 样式是否可以定制一下

### ISSUE THREAD

**Issue by reposkeeper** [FishionYu/typora-blubook-theme#7]
![image](https://user-images.githubusercontent.com/23925710/90720392-06f1f900-e2e9-11ea-8581-3513b55b3fe8.png)
上面是我自己借鉴 ursine 这个主题，给 vue 的主题改的

**Comment by FishionYu** [comment]
才发现，todo样式有严重的问题，我会尽快调整一个出来

**Comment by reposkeeper** [comment]
![image](https://user-images.githubusercontent.com/23925710/90749674-54c92a00-e306-11ea-82a3-bfa9cda9ef9d.png)
我自己先改了一个用，其实更喜欢 mac 中 note 的那个圆形的 todo 样式

**Comment by FishionYu** [comment]
看起来不错，你可以提交一个pull request

**Comment by FishionYu** [comment]
![](https://cdn.jsdelivr.net/gh/FishionYu/Rayyu-sPic@master/img/ENt7zp.png)
