### ISSUE TITLE
部分中文字符显示异常

### ISSUE THREAD

**Issue by reposkeeper** [FishionYu/typora-blubook-theme#8]
![image](https://user-images.githubusercontent.com/23925710/91248930-66885280-e788-11ea-8b21-44988f4cf72c.png)
如上图中，`理`  和  `行` 都是看起来像是加粗了。这个有办法解决嘛？

**Comment by FishionYu** [comment]
这是windows下的吗？这个问题感觉灰常奇怪...

**Comment by reposkeeper** [comment]
是在 mac 10.15.6 下，很多字都会有这种问题

**Comment by FishionYu** [comment]
复现了，我在字体册把未来荧黑停用掉就出现这个问题了，初步判断应该是woff字体的问题

临时解决方法是：安装`未来荧黑字体`，开源库在[这里](https://github.com/welai/glow-sans/releases)，下载GlowSansSC-Normal-v0.9.zip

彻底解决需要时间我测试一下

**Comment by reposkeeper** [comment]
非常感谢，我试一下
