### ISSUE TITLE
英文模式下的单引号问题

### ISSUE THREAD

**Issue by TAN-ZIXUAN** [FishionYu/typora-blubook-theme#9]
![image](https://user-images.githubusercontent.com/56602039/91357613-61d29700-e7a6-11ea-85cb-fdbe6864e30e.png)
这个英文单引号没有正确显示，中间空的有点多

**Comment by FishionYu** [comment]
我在Mac端没有遇到这个问题，可能需要你确认一下情况，让我来再测一下
是windows的版本吗，是否是切换的英文输入法输入的，Typora的设置项有没有开智能转换

**Comment by TAN-ZIXUAN** [comment]
我换了typora自带的主题，单引号正常，切换了中英文输入法，但是我发现它中英文单引号没有区别
windows 10 的 20175.1000。

**Comment by FishionYu** [comment]
晚些时候我会在windows测试一下

**Comment by TAN-ZIXUAN** [comment]
我刚刚发现typora拼写检查可以把错误的单引号改对， 但是我打不出来这个单引号。
![image](https://user-images.githubusercontent.com/56602039/91387663-9d8f5000-e7ea-11ea-9c96-a43e310f088c.png)
![image](https://user-images.githubusercontent.com/56602039/91387721-b6980100-e7ea-11ea-9e09-f476d9ad7156.png)
第二张图里，第二个引号已经变成正确的那种了，中间的空隙也可以删除了。
![image](https://user-images.githubusercontent.com/56602039/91387786-d92a1a00-e7ea-11ea-86af-edde4021ed9e.png)

**Comment by FishionYu** [comment]
可能是typora编辑器或者未来荧黑字体的问题，我会改一下字体引用逻辑试一下

**Comment by FishionYu** [comment]
你试一下安装未来荧黑字体，开源库在[这里](https://github.com/welai/glow-sans/releases)，或点这里直接下载[GlowSansSC-Normal-v0.9.zip](https://github.com/welai/glow-sans/releases/download/v0.9/GlowSansSC-Normal-v0.9.zip)，然后安装看看问题会不会出现

**Comment by TAN-ZIXUAN** [comment]
> 你试一下安装未来荧黑字体，开源库在[这里](https://github.com/welai/glow-sans/releases)，或点这里直接下载[GlowSansSC-Normal-v0.9.zip](https://github.com/welai/glow-sans/releases/download/v0.9/GlowSansSC-Normal-v0.9.zip)，然后安装看看问题会不会出现

我安装了字体，还是有这个问题
